name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Select Xcode
        run: sh .github/select-xcode.sh

      - name: Test Build
        run: swift build -Xswiftc -warnings-as-errors --enable-experimental-prebuilts

      - name: Run Tests
        run: swift test -Xswiftc -warnings-as-errors --enable-experimental-prebuilts
  format:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Select Xcode
        run: sh .github/select-xcode.sh

      - name: Run formatter
        run: sh .github/format.sh

      - name: Check if formatting changes exist
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Formatting changes detected."
            git status --porcelain
            git diff
            exit 1
          fi
